version: "3"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    entrypoint: ["/app/wait-for-it.sh", "postgres:5432", "--"]
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]



